charVar = {
    name: "clownQueen",
    displayName: "Clown Clan Leader",
    energy: 100,
    maxEnergy: 100,
    pPower: 10,
    kPower: 10,
    offense: ["p", "p", "k", "k", "k", "g", "g", "g"],
    clothingLevel: 2,
    money: 50 + Math.floor(Math.random() * 50),
    cock: false,
    p: "pose",
    weakspot: [0],
    base: "f_sc",
    domination: { pose: "kneel", pose1: "kneel", gif: "gif_buttholelick.gif", gif1: "png_buttholelick.png", stats: ["giveOralFemale"] },
    domFuckem: { pose: "fuck", pose1: "fuck1", gif: "gif_fuck.gif", gif1: "png_fuck1.png", stats: ["fuckPussy"] },
    domPowerbottom: { pose: "takeit", pose1: "takeit1", gif: "gif_stickbutt.gif", gif1: "png_stickbutt.png", status: [""] },
    domMenu: ["lb_domFuckem", "lb_domPowerbottom"],
    loss: "HONK.. damn....",
    intro: "I will HONK you in the HONK with my HONK!!",
    win: "HAHAHAHAHAHAHAHAHA It's funny how you lose HONK",
    submit: "Eat ass slut HONK"
};